const actions = {
   UPDATE_CURRENT_USER: "UPDATE_CURRENT_USER",
   STORE_ALL_QUESTIONS: "STORE_ALL_QUESTIONS",
   STORE_ANSWERABLE_QUESTION: "STORE_ANSWERABLE_QUESTION",
   UPDATE_CREATABLE_ANSWER: "UPDATE_CREATABLE_ANSWER",
};

export default actions;
